[2022-12-27 16:40:37,221] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: crypto_data_etl_auto_train_model.train_model 2022-12-25T07:00:00+00:00 [queued]>
[2022-12-27 16:40:37,229] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: crypto_data_etl_auto_train_model.train_model 2022-12-25T07:00:00+00:00 [queued]>
[2022-12-27 16:40:37,230] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 16:40:37,230] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-12-27 16:40:37,230] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 16:40:37,241] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): train_model> on 2022-12-25T07:00:00+00:00
[2022-12-27 16:40:37,248] {standard_task_runner.py:52} INFO - Started process 31093 to run task
[2022-12-27 16:40:37,251] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_data_etl_auto_train_model', 'train_model', '2022-12-25T07:00:00+00:00', '--job-id', '1085', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl.py', '--cfg-path', '/tmp/tmphl1xxssl', '--error-file', '/tmp/tmpeji659t9']
[2022-12-27 16:40:37,254] {standard_task_runner.py:77} INFO - Job 1085: Subtask train_model
[2022-12-27 16:40:37,295] {logging_mixin.py:104} INFO - Running <TaskInstance: crypto_data_etl_auto_train_model.train_model 2022-12-25T07:00:00+00:00 [running]> on host 2a76951a993b
[2022-12-27 16:40:37,327] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=VMD
AIRFLOW_CTX_DAG_ID=crypto_data_etl_auto_train_model
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-25T07:00:00+00:00
[2022-12-27 16:40:37,335] {base.py:74} INFO - Using connection to: id: postgres_con. Host: host.docker.internal, Port: 5432, Schema: doan, Login: postgres, Password: XXXXXXXX, extra: None
[2022-12-27 16:40:37,371] {base.py:74} INFO - Using connection to: id: postgres_con. Host: host.docker.internal, Port: 5432, Schema: doan, Login: postgres, Password: XXXXXXXX, extra: None
[2022-12-27 16:40:38,940] {logging_mixin.py:104} INFO - Epoch 1/50
[2022-12-27 16:40:42,307] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-27 16:40:42,319] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 31093
[2022-12-27 16:40:42,319] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-27 16:40:42,412] {process_utils.py:66} INFO - Process psutil.Process(pid=31093, status='terminated', exitcode=0, started='16:40:36') (31093) terminated with exit code 0
