[2022-12-27 18:24:09,134] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: crypto_data_etl_auto_train_model.get_tweet_and_analysis_sentiment 2022-12-26T07:00:00+00:00 [queued]>
[2022-12-27 18:24:09,143] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: crypto_data_etl_auto_train_model.get_tweet_and_analysis_sentiment 2022-12-26T07:00:00+00:00 [queued]>
[2022-12-27 18:24:09,143] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 18:24:09,143] {taskinstance.py:1043} INFO - Starting attempt 3 of 8
[2022-12-27 18:24:09,144] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-12-27 18:24:09,154] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): get_tweet_and_analysis_sentiment> on 2022-12-26T07:00:00+00:00
[2022-12-27 18:24:09,161] {standard_task_runner.py:52} INFO - Started process 11549 to run task
[2022-12-27 18:24:09,165] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_data_etl_auto_train_model', 'get_tweet_and_analysis_sentiment', '2022-12-26T07:00:00+00:00', '--job-id', '1098', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl.py', '--cfg-path', '/tmp/tmpap8yhii0', '--error-file', '/tmp/tmp6u2pkv71']
[2022-12-27 18:24:09,169] {standard_task_runner.py:77} INFO - Job 1098: Subtask get_tweet_and_analysis_sentiment
[2022-12-27 18:24:09,206] {logging_mixin.py:104} INFO - Running <TaskInstance: crypto_data_etl_auto_train_model.get_tweet_and_analysis_sentiment 2022-12-26T07:00:00+00:00 [running]> on host 2a76951a993b
[2022-12-27 18:24:09,237] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=VMD
AIRFLOW_CTX_DAG_ID=crypto_data_etl_auto_train_model
AIRFLOW_CTX_TASK_ID=get_tweet_and_analysis_sentiment
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T07:00:00+00:00
[2022-12-27 18:24:09,241] {logging_mixin.py:104} INFO - scrawling for VitalikButerin
[2022-12-27 18:24:09,241] {logging_mixin.py:104} INFO - 
[2022-12-27 18:24:09,242] {twitter.py:100} INFO - Retrieving guest token from search page
[2022-12-27 18:24:09,244] {base.py:56} INFO - Retrieving https://twitter.com/search?f=live&lang=en&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&src=spelling_expansion_revert_click
[2022-12-27 18:24:09,979] {twitter.py:135} INFO - Retrieving scroll page None
[2022-12-27 18:24:09,980] {base.py:56} INFO - Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment
[2022-12-27 18:24:10,012] {base.py:69} WARNING - Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa186b0bd30>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),), retrying
[2022-12-27 18:24:10,013] {base.py:90} INFO - Waiting 1 seconds
[2022-12-27 18:24:11,015] {base.py:56} INFO - Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment
[2022-12-27 18:24:11,019] {base.py:69} WARNING - Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0e534def0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),), retrying
[2022-12-27 18:24:11,020] {base.py:90} INFO - Waiting 2 seconds
[2022-12-27 18:24:13,023] {base.py:56} INFO - Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment
[2022-12-27 18:24:13,027] {base.py:69} WARNING - Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa186b0ba58>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),), retrying
[2022-12-27 18:24:13,028] {base.py:90} INFO - Waiting 4 seconds
[2022-12-27 18:24:17,031] {base.py:56} INFO - Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment
[2022-12-27 18:24:17,034] {base.py:69} ERROR - Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa186b0b630>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))",),)
[2022-12-27 18:24:17,034] {base.py:94} CRITICAL - 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up.
[2022-12-27 18:24:17,035] {taskinstance.py:1455} ERROR - 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/datacrawl.py", line 116, in get_tweet_and_analysis_sentiment
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper("from:"+ user + 'bitcoin' + ' since:' + yesterday + ' until:' + now).get_items()):
  File "/home/airflow/.local/lib/python3.6/site-packages/snscrape/modules/twitter.py", line 168, in get_items
    r = self._get('https://api.twitter.com/2/search/adaptive.json', params = params, headers = headers, responseOkCallback = self._check_scroll_response)
  File "/home/airflow/.local/lib/python3.6/site-packages/snscrape/base.py", line 99, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/snscrape/base.py", line 95, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_composer_source=true&include_ext_alt_text=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3AVitalikButerin%0Abitcoin+since%3A2022-12-26+until%3A2022-12-27&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%252CcameraMoment failed, giving up.
[2022-12-27 18:24:17,039] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_etl_auto_train_model, task_id=get_tweet_and_analysis_sentiment, execution_date=20221226T070000, start_date=20221227T182409, end_date=20221227T182417
[2022-12-27 18:24:17,085] {local_task_job.py:146} INFO - Task exited with return code 1
